DROP DATABASE IF EXISTS examen_fotos;
CREATE DATABASE examen_fotos CHARSET utf8mb4;
USE examen_fotos;

CREATE TABLE fotos(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(50) NOT NULL,
    descripcion VARCHAR(200) NOT NULL,
    url TEXT NOT NULL,
    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    votos INT NOT NULL
);

CREATE TABLE comentarios(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    usuario VARCHAR(50) NOT NULL,
    comentario VARCHAR(200) NOT NULL,
    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    foto_id INT UNSIGNED,
    CONSTRAINT fk_foto FOREIGN KEY(foto_id) REFERENCES foto(id)
);